// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2-OF-jVHArKKdnO80R1A68HmYWxCKXgk',
    appId: '1:11734943862:web:6383e763c32645c9e83757',
    messagingSenderId: '11734943862',
    projectId: 'waggly-test-notification',
    authDomain: 'waggly-test-notification.firebaseapp.com',
    storageBucket: 'waggly-test-notification.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ01lB927JdKSeD2JyXuQlTrrGnSbmTyI',
    appId: '1:11734943862:android:2134645d010a30f6e83757',
    messagingSenderId: '11734943862',
    projectId: 'waggly-test-notification',
    storageBucket: 'waggly-test-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwy9eg7OQSnE3PQ99Raq1UzuEiOLhviuo',
    appId: '1:11734943862:ios:ff1cb65be45f1a4fe83757',
    messagingSenderId: '11734943862',
    projectId: 'waggly-test-notification',
    storageBucket: 'waggly-test-notification.appspot.com',
    iosClientId: '11734943862-93i672e0r9a4i027r1tba6fnuejb1rnf.apps.googleusercontent.com',
    iosBundleId: 'com.waggly.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwy9eg7OQSnE3PQ99Raq1UzuEiOLhviuo',
    appId: '1:11734943862:ios:bfe72ece18a93471e83757',
    messagingSenderId: '11734943862',
    projectId: 'waggly-test-notification',
    storageBucket: 'waggly-test-notification.appspot.com',
    iosClientId: '11734943862-ff1rbhjkqf5t3bto4diam1sl9tqai0u1.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
